// @flow

export default {
  USER_ACCESS_ACKNOWLEDGE_FAILED_OPERATION: 'USER_ACCESS_ACKNOWLEDGE_FAILED_OPERATION',

  USER_ACCESS_GET_CURRENT_USER: 'USER_ACCESS_GET_CURRENT_USER',
  USER_ACCESS_GET_CURRENT_USER_SUCCEEDED: 'USER_ACCESS_GET_CURRENT_USER_SUCCEEDED',
  USER_ACCESS_GET_CURRENT_USER_FAILED: 'USER_ACCESS_GET_CURRENT_USER_FAILED',

  USER_ACCESS_RESET_GET_CURRENT_USER_STATUS: 'USER_ACCESS_RESET_GET_CURRENT_USER_STATUS',
  USER_ACCESS_GET_CURRENT_USER_IN_PROGRESS: 'USER_ACCESS_GET_CURRENT_USER_IN_PROGRESS',

  USER_ACCESS_SIGNUP_WITH_USERNAME_AND_PASSWORD: 'USER_ACCESS_SIGNUP_WITH_USERNAME_AND_PASSWORD',
  USER_ACCESS_SIGNUP_WITH_USERNAME_AND_PASSWORD_SUCCEEDED: 'USER_ACCESS_SIGNUP_WITH_USERNAME_AND_PASSWORD_SUCCEEDED',
  USER_ACCESS_SIGNUP_WITH_USERNAME_AND_PASSWORD_FAILED: 'USER_ACCESS_SIGNUP_WITH_USERNAME_AND_PASSWORD_FAILED',

  USER_ACCESS_RESET_SIGNUP_STATUS: 'USER_ACCESS_RESET_SIGNUP_STATUS',
  USER_ACCESS_SIGNUP_IN_PROGRESS: 'USER_ACCESS_SIGNUP_IN_PROGRESS',

  USER_ACCESS_SIGNIN_WITH_USERNAME_AND_PASSWORD: 'USER_ACCESS_SIGNIN_WITH_USERNAME_AND_PASSWORD',
  USER_ACCESS_SIGNIN_WITH_USERNAME_AND_PASSWORD_SUCCEEDED: 'USER_ACCESS_SIGNIN_WITH_USERNAME_AND_PASSWORD_SUCCEEDED',
  USER_ACCESS_SIGNIN_WITH_USERNAME_AND_PASSWORD_FAILED: 'USER_ACCESS_SIGNIN_WITH_USERNAME_AND_PASSWORD_FAILED',

  USER_ACCESS_RESET_SIGNIN_STATUS: 'USER_ACCESS_RESET_SIGNIN_STATUS',
  USER_ACCESS_SIGNIN_IN_PROGRESS: 'USER_ACCESS_SIGNIN_IN_PROGRESS',

  USER_ACCESS_SIGNOUT: 'USER_ACCESS_SIGNOUT',
  USER_ACCESS_SIGNOUT_SUCCEEDED: 'USER_ACCESS_SIGNOUT_SUCCEEDED',
  USER_ACCESS_SIGNOUT_FAILED: 'USER_ACCESS_SIGNOUT_FAILED',

  USER_ACCESS_RESET_SIGNOUT_STATUS: 'USER_ACCESS_RESET_SIGNOUT_STATUS',
  USER_ACCESS_SIGNOUT_IN_PROGRESS: 'USER_ACCESS_SIGNOUT_IN_PROGRESS',
};
